//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/InputActions/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""Jogador"",
            ""id"": ""2cac321c-c909-4a1c-a3db-77b0a9890784"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""a10b4d47-eabb-43fe-ada0-db6e7953532d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Action"",
                    ""type"": ""Button"",
                    ""id"": ""9d7334ce-c852-4550-913a-f58cb1c3a675"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActionInVehicle"",
                    ""type"": ""Button"",
                    ""id"": ""89621a76-1c40-4919-ba0b-75edee686bc7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MenuInteractionConfirmation"",
                    ""type"": ""Button"",
                    ""id"": ""bd4e063f-70f2-4c54-98b6-4f2835fd9b74"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MenuPauseInteraction"",
                    ""type"": ""Button"",
                    ""id"": ""e72c0646-d2ee-4fde-8593-c64e9e6718c0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MenuInventoryInteraction"",
                    ""type"": ""Button"",
                    ""id"": ""98d1c782-5604-434a-855b-724df16e8ea4"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pointer"",
                    ""type"": ""Value"",
                    ""id"": ""9896f0a8-d32a-4a2f-bafa-479392f933ec"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Click"",
                    ""type"": ""Button"",
                    ""id"": ""a18e42a5-ca45-4b1d-9339-13f9b3513e12"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""d0bfe5c7-1f85-4087-bccc-931da4286c71"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Keyboard WASD"",
                    ""id"": ""e8a716e4-17af-41a9-8100-e139b3cfae22"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""down"",
                    ""id"": ""ebd827c4-9f86-475d-ab1d-9308083512ba"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""02fb3536-5521-4f84-8384-5a824f89cc6b"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""f5b77695-ed21-4ccb-a86b-d5d580dd5be8"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Controller Joystick"",
                    ""id"": ""c82172c3-8963-4c3a-b91a-efbc6b7f12c2"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""down"",
                    ""id"": ""69f32ff7-d01f-46cf-ada0-530f004fd874"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""7d79aeeb-ee4f-4622-ae1d-d5b7215a0994"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""db085e95-b716-47ea-8546-827522c2a3e7"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Mobile Joystick"",
                    ""id"": ""463778f3-51f1-492c-b12f-6cef63accae2"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""25aa1eef-ed4d-4cb3-b8d1-0bec80516a36"",
                    ""path"": ""<AndroidJoystick>/stick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""82bfda9e-3337-40c0-98b5-317615e0057d"",
                    ""path"": ""<AndroidJoystick>/stick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""be0891a7-999f-4ea1-ba07-3f8e40fe2c81"",
                    ""path"": ""<AndroidJoystick>/stick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""4590335e-27ec-46fe-a20c-104153e7653d"",
                    ""path"": ""<AndroidJoystick>/stick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Keyboard ARROWS"",
                    ""id"": ""9cc6a14c-45ae-4b7d-a425-e0d2d7ae451a"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""down"",
                    ""id"": ""82d1cee1-1b6f-4ade-864b-fd70c9c3bced"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""04c085cf-dc96-4302-b3b5-60dd21800fed"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""a4ac2605-dbda-43f5-a574-3f4c043894ef"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""d4a670d9-586f-4d6d-9652-df35b5015292"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8720556b-4c0b-4c65-b9d4-5f456fb40fc7"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ec1aefa6-bfbd-41dd-b359-e0765444db11"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuInteractionConfirmation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cc182092-01ee-4377-bcd6-777349439c4a"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuInteractionConfirmation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c6a8245a-f638-4c2b-9b6a-d672e87a6afe"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActionInVehicle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9cd9d17c-e87f-4b21-8949-bc0f4a7a360f"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActionInVehicle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6ba292f3-64bb-4ac0-99a1-1b4f4fe12c40"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuPauseInteraction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""be991153-2c9b-4bf9-9926-a116a1283feb"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuPauseInteraction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dbb0dc60-3ea7-4ab1-b704-bb2d4a1c02ba"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuInventoryInteraction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""724c0b90-6df8-48a0-b132-12bcc0024d71"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuInventoryInteraction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""00ced687-9ee5-4c73-bacf-1f79753b83ca"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pointer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f52971b9-3b98-4dfd-91e8-4ac9ad340b8e"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d24e01c2-3c5a-408f-acf1-2be13ba53f47"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a2d94210-f9ea-4e73-bb29-617aee1cdec6"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Jogador
        m_Jogador = asset.FindActionMap("Jogador", throwIfNotFound: true);
        m_Jogador_Movement = m_Jogador.FindAction("Movement", throwIfNotFound: true);
        m_Jogador_Action = m_Jogador.FindAction("Action", throwIfNotFound: true);
        m_Jogador_ActionInVehicle = m_Jogador.FindAction("ActionInVehicle", throwIfNotFound: true);
        m_Jogador_MenuInteractionConfirmation = m_Jogador.FindAction("MenuInteractionConfirmation", throwIfNotFound: true);
        m_Jogador_MenuPauseInteraction = m_Jogador.FindAction("MenuPauseInteraction", throwIfNotFound: true);
        m_Jogador_MenuInventoryInteraction = m_Jogador.FindAction("MenuInventoryInteraction", throwIfNotFound: true);
        m_Jogador_Pointer = m_Jogador.FindAction("Pointer", throwIfNotFound: true);
        m_Jogador_Click = m_Jogador.FindAction("Click", throwIfNotFound: true);
        m_Jogador_Jump = m_Jogador.FindAction("Jump", throwIfNotFound: true);
    }

    ~@PlayerControls()
    {
        UnityEngine.Debug.Assert(!m_Jogador.enabled, "This will cause a leak and performance issues, PlayerControls.Jogador.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Jogador
    private readonly InputActionMap m_Jogador;
    private List<IJogadorActions> m_JogadorActionsCallbackInterfaces = new List<IJogadorActions>();
    private readonly InputAction m_Jogador_Movement;
    private readonly InputAction m_Jogador_Action;
    private readonly InputAction m_Jogador_ActionInVehicle;
    private readonly InputAction m_Jogador_MenuInteractionConfirmation;
    private readonly InputAction m_Jogador_MenuPauseInteraction;
    private readonly InputAction m_Jogador_MenuInventoryInteraction;
    private readonly InputAction m_Jogador_Pointer;
    private readonly InputAction m_Jogador_Click;
    private readonly InputAction m_Jogador_Jump;
    public struct JogadorActions
    {
        private @PlayerControls m_Wrapper;
        public JogadorActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_Jogador_Movement;
        public InputAction @Action => m_Wrapper.m_Jogador_Action;
        public InputAction @ActionInVehicle => m_Wrapper.m_Jogador_ActionInVehicle;
        public InputAction @MenuInteractionConfirmation => m_Wrapper.m_Jogador_MenuInteractionConfirmation;
        public InputAction @MenuPauseInteraction => m_Wrapper.m_Jogador_MenuPauseInteraction;
        public InputAction @MenuInventoryInteraction => m_Wrapper.m_Jogador_MenuInventoryInteraction;
        public InputAction @Pointer => m_Wrapper.m_Jogador_Pointer;
        public InputAction @Click => m_Wrapper.m_Jogador_Click;
        public InputAction @Jump => m_Wrapper.m_Jogador_Jump;
        public InputActionMap Get() { return m_Wrapper.m_Jogador; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(JogadorActions set) { return set.Get(); }
        public void AddCallbacks(IJogadorActions instance)
        {
            if (instance == null || m_Wrapper.m_JogadorActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_JogadorActionsCallbackInterfaces.Add(instance);
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @Action.started += instance.OnAction;
            @Action.performed += instance.OnAction;
            @Action.canceled += instance.OnAction;
            @ActionInVehicle.started += instance.OnActionInVehicle;
            @ActionInVehicle.performed += instance.OnActionInVehicle;
            @ActionInVehicle.canceled += instance.OnActionInVehicle;
            @MenuInteractionConfirmation.started += instance.OnMenuInteractionConfirmation;
            @MenuInteractionConfirmation.performed += instance.OnMenuInteractionConfirmation;
            @MenuInteractionConfirmation.canceled += instance.OnMenuInteractionConfirmation;
            @MenuPauseInteraction.started += instance.OnMenuPauseInteraction;
            @MenuPauseInteraction.performed += instance.OnMenuPauseInteraction;
            @MenuPauseInteraction.canceled += instance.OnMenuPauseInteraction;
            @MenuInventoryInteraction.started += instance.OnMenuInventoryInteraction;
            @MenuInventoryInteraction.performed += instance.OnMenuInventoryInteraction;
            @MenuInventoryInteraction.canceled += instance.OnMenuInventoryInteraction;
            @Pointer.started += instance.OnPointer;
            @Pointer.performed += instance.OnPointer;
            @Pointer.canceled += instance.OnPointer;
            @Click.started += instance.OnClick;
            @Click.performed += instance.OnClick;
            @Click.canceled += instance.OnClick;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
        }

        private void UnregisterCallbacks(IJogadorActions instance)
        {
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @Action.started -= instance.OnAction;
            @Action.performed -= instance.OnAction;
            @Action.canceled -= instance.OnAction;
            @ActionInVehicle.started -= instance.OnActionInVehicle;
            @ActionInVehicle.performed -= instance.OnActionInVehicle;
            @ActionInVehicle.canceled -= instance.OnActionInVehicle;
            @MenuInteractionConfirmation.started -= instance.OnMenuInteractionConfirmation;
            @MenuInteractionConfirmation.performed -= instance.OnMenuInteractionConfirmation;
            @MenuInteractionConfirmation.canceled -= instance.OnMenuInteractionConfirmation;
            @MenuPauseInteraction.started -= instance.OnMenuPauseInteraction;
            @MenuPauseInteraction.performed -= instance.OnMenuPauseInteraction;
            @MenuPauseInteraction.canceled -= instance.OnMenuPauseInteraction;
            @MenuInventoryInteraction.started -= instance.OnMenuInventoryInteraction;
            @MenuInventoryInteraction.performed -= instance.OnMenuInventoryInteraction;
            @MenuInventoryInteraction.canceled -= instance.OnMenuInventoryInteraction;
            @Pointer.started -= instance.OnPointer;
            @Pointer.performed -= instance.OnPointer;
            @Pointer.canceled -= instance.OnPointer;
            @Click.started -= instance.OnClick;
            @Click.performed -= instance.OnClick;
            @Click.canceled -= instance.OnClick;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
        }

        public void RemoveCallbacks(IJogadorActions instance)
        {
            if (m_Wrapper.m_JogadorActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IJogadorActions instance)
        {
            foreach (var item in m_Wrapper.m_JogadorActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_JogadorActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public JogadorActions @Jogador => new JogadorActions(this);
    public interface IJogadorActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnAction(InputAction.CallbackContext context);
        void OnActionInVehicle(InputAction.CallbackContext context);
        void OnMenuInteractionConfirmation(InputAction.CallbackContext context);
        void OnMenuPauseInteraction(InputAction.CallbackContext context);
        void OnMenuInventoryInteraction(InputAction.CallbackContext context);
        void OnPointer(InputAction.CallbackContext context);
        void OnClick(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
    }
}
